name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# TODO:
# - Unit Testing job
# - GitHub Releases
# - Mac (DMG), Linux (AppImage, Snap, Flatpak?) and Windows Builds (Msi)

# $GITHUB_WORKSPACE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jurplel/install-qt-action@v2
        with:
          modules: qtwebengine
      - name: Qmake
        run: qmake
      - name: Qmake
        run: make
      - name: Output
        run: ls -l
