name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# TODO:
# - Unit Testing job
# - GitHub Releases
# - Mac (DMG), Linux (AppImage, Snap, Flatpak?) and Windows Builds (Msi)

# $GITHUB_WORKSPACE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      - name: Make?
        run: make --help
      - name: Qmake?
        run: qmake --help
